/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poc.view;

//import java.awt.Dimension;
//import javax.swing.JComponent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JMenuBar;
import poc.model.Campeonato;
import poc.model.Campo;
import poc.model.Time;
/**
 *
 * @author Leandro
 */
public class AdicionarTime extends javax.swing.JInternalFrame {
    private Campeonato campeonato;
    private Time time;
    private Campo campo;
    private Time arrayTime[];
    /**
     * Creates new form AdicionarTimee
     */
    public AdicionarTime() {
        initComponents();
        //removeTitleBar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNome = new javax.swing.JLabel();
        labelAbreviacao = new javax.swing.JLabel();
        labelPrioridade = new javax.swing.JLabel();
        buttonAddOutro = new javax.swing.JButton();
        buttonConfirmar = new javax.swing.JButton();
        butttonCancelar = new javax.swing.JButton();
        textNome = new javax.swing.JTextField();
        textAbreviacao = new javax.swing.JTextField();
        comboPrioridade = new javax.swing.JComboBox<>();
        labelEscudo = new javax.swing.JLabel();
        buttonEscudo = new javax.swing.JButton();
        labelCampo = new javax.swing.JLabel();
        textCampo = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Adicionar Time");
        setToolTipText("");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setDoubleBuffered(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/poc/view/icons/addTime.png"))); // NOI18N

        labelNome.setText("Nome");

        labelAbreviacao.setText("Abreviação");

        labelPrioridade.setText("Prioridade");

        buttonAddOutro.setText("Confirmar e Adicionar Outro");
        buttonAddOutro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddOutroActionPerformed(evt);
            }
        });

        buttonConfirmar.setText("Confirmar");
        buttonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmarActionPerformed(evt);
            }
        });

        butttonCancelar.setText("Cancelar");
        butttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butttonCancelarActionPerformed(evt);
            }
        });

        comboPrioridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelEscudo.setText("Escudo");

        buttonEscudo.setText("Importar...");
        buttonEscudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEscudoActionPerformed(evt);
            }
        });

        labelCampo.setText("Campo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butttonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(buttonConfirmar)
                        .addGap(18, 18, 18)
                        .addComponent(buttonAddOutro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAbreviacao)
                                    .addComponent(labelNome))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textAbreviacao)
                                    .addComponent(textNome)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPrioridade)
                                    .addComponent(labelEscudo)
                                    .addComponent(labelCampo))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboPrioridade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonEscudo)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(textCampo))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAbreviacao)
                    .addComponent(textAbreviacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrioridade)
                    .addComponent(comboPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEscudo)
                    .addComponent(buttonEscudo))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCampo)
                    .addComponent(textCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddOutro)
                    .addComponent(buttonConfirmar)
                    .addComponent(butttonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butttonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_butttonCancelarActionPerformed

    private void buttonEscudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEscudoActionPerformed
        try {
            // TODO add your handling code here:
            Runtime.getRuntime().exec("explorer");
        } catch (IOException ex) {
            Logger.getLogger(AdicionarTime.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonEscudoActionPerformed

    private void buttonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmarActionPerformed
        // TODO add your handling code here:
        time = new Time();
        campo = new Campo();
        campeonato = new Campeonato();
        time.setNome(labelNome.getText());
        campo.setNome(labelCampo.getText());
        time.setCampo(campo);
        time.setPrioridade(comboPrioridade.getItemCount());
    }//GEN-LAST:event_buttonConfirmarActionPerformed

    private void buttonAddOutroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddOutroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buttonAddOutroActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddOutro;
    private javax.swing.JButton buttonConfirmar;
    private javax.swing.JButton buttonEscudo;
    private javax.swing.JButton butttonCancelar;
    private javax.swing.JComboBox<String> comboPrioridade;
    private javax.swing.JLabel labelAbreviacao;
    private javax.swing.JLabel labelCampo;
    private javax.swing.JLabel labelEscudo;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPrioridade;
    private javax.swing.JTextField textAbreviacao;
    private javax.swing.JTextField textCampo;
    private javax.swing.JTextField textNome;
    // End of variables declaration//GEN-END:variables
}
