/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poc.view;

//import java.awt.Dimension;
//import javax.swing.JComponent;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;
import poc.control.CampeonatoController;
import poc.control.CampoController;
import poc.control.TimeController;
import poc.model.Campeonato;
import poc.model.Campo;
import poc.model.Time;

/**
 *
 * @author Leandro
 */
public class AtualizarTime extends javax.swing.JInternalFrame {

    private Campeonato campeonato;
    private TimeController timeControl;
    private CampoController campoControl;
    private CampeonatoController champControl;
    private Campo campo;
    private Time time;
    private ArrayList<Time> times = new ArrayList<Time>();
    private int contador = 0;

    /**
     * Creates new form AdicionarTimee
     */
    public AtualizarTime(Campeonato campeonato) {
        initComponents();
        this.campeonato = campeonato;
        organizarCombo();
        //removeTitleBar();
    }

    public void organizarCombo() {
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();

        times = campeonato.getTimes();

        for (Time time1 : times) {
            modeloCombo.addElement(time1.getCodigo());
        }

        comboCodigo.setModel(modeloCombo);
    }

    public void organizarComboPrioridade(int prioridade) {
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();

        times = campeonato.getTimes();

        modeloCombo.addElement(prioridade);
        
        for (int i = 1; i < 101; i++) {
            if (verificaPrioridades(times, i) == false) {
                modeloCombo.addElement(i);
            }
        }

        comboPrioridade.setModel(modeloCombo);
    }

    public boolean verificaPrioridades(ArrayList<Time> times, int i) {

        for (Time time1 : times) {
            if (time1.getPrioridade() == i) {
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seletorArquivos = new javax.swing.JFileChooser();
        labelNome = new javax.swing.JLabel();
        labelAbreviacao = new javax.swing.JLabel();
        labelPrioridade = new javax.swing.JLabel();
        buttonConfirmar = new javax.swing.JButton();
        butttonCancelar = new javax.swing.JButton();
        textNome = new javax.swing.JTextField();
        comboCodigo = new javax.swing.JComboBox<>();
        labelCampo = new javax.swing.JLabel();
        textCampo = new javax.swing.JTextField();
        textAbreviacao = new javax.swing.JTextField();
        labelNome1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        comboPrioridade = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Atualizar Time");
        setToolTipText("");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setDoubleBuffered(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/poc/view/icons/atualizar.png"))); // NOI18N

        labelNome.setText("Nome:");

        labelAbreviacao.setText("Abreviação:");

        labelPrioridade.setText("Prioridade:");

        buttonConfirmar.setText("Confirmar");
        buttonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmarActionPerformed(evt);
            }
        });

        butttonCancelar.setText("Cancelar");
        butttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butttonCancelarActionPerformed(evt);
            }
        });

        comboCodigo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));
        comboCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCodigoActionPerformed(evt);
            }
        });

        labelCampo.setText("Campo:");

        labelNome1.setText("Código:");

        comboPrioridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(butttonCancelar)
                        .addGap(262, 262, 262)
                        .addComponent(buttonConfirmar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNome1)
                                .addGap(47, 47, 47)
                                .addComponent(comboCodigo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCampo)
                                    .addComponent(labelAbreviacao, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelNome))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(textCampo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textNome)
                                            .addComponent(textAbreviacao)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPrioridade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboPrioridade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAbreviacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAbreviacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrioridade)
                    .addComponent(comboPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCampo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonConfirmar)
                    .addComponent(butttonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butttonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_butttonCancelarActionPerformed

    private void buttonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmarActionPerformed
        // TODO add your handling code here:
        campoControl = new CampoController();
        champControl = new CampeonatoController();
        timeControl = new TimeController();
        times = campeonato.getTimes();

        System.out.println("CONTADOR => " + contador);
        time = times.get(contador);

        System.out.println("TESTE");
        System.out.println("NOME: " + time.getNome());
        System.out.println("ABREVIACAO" + time.getAbreviacao());
        System.out.println("CODIGO: " + time.getCodigo());
        System.out.println("PRIORIDADE: " + time.getPrioridade());

        int selecionado = Integer.parseInt(comboPrioridade.getSelectedItem().toString());
        time.setNome(textNome.getText());
        time.setAbreviacao(textAbreviacao.getText());
        campo = time.getCampo();
        campo.setNome(textCampo.getText());
        time.setCampo(campo);
        time.setPrioridade(selecionado);

    }//GEN-LAST:event_buttonConfirmarActionPerformed

    private void comboCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCodigoActionPerformed
        // TODO add your handling code here:
        times = campeonato.getTimes();
        int selecionado = Integer.parseInt(comboCodigo.getSelectedItem().toString());
        int contador = 0;

        for (Time time1 : times) {
            if (time1.getCodigo() == selecionado) {
                organizarComboPrioridade(time1.getPrioridade());
                textNome.setText(time1.getNome());
                System.out.println(time1.getAbreviacao());
                textAbreviacao.setText(time1.getAbreviacao());
                textCampo.setText(time1.getCampo().getNome());
                //comboPrioridade.setSelectedIndex();
                break;
            }
            contador++;
        }

        this.contador = contador;
    }//GEN-LAST:event_comboCodigoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConfirmar;
    private javax.swing.JButton butttonCancelar;
    private javax.swing.JComboBox<String> comboCodigo;
    private javax.swing.JComboBox<String> comboPrioridade;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAbreviacao;
    private javax.swing.JLabel labelCampo;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNome1;
    private javax.swing.JLabel labelPrioridade;
    private javax.swing.JFileChooser seletorArquivos;
    private javax.swing.JTextField textAbreviacao;
    private javax.swing.JTextField textCampo;
    private javax.swing.JTextField textNome;
    // End of variables declaration//GEN-END:variables

    private void abrirSeletorArquivos() {
        int returnVal = seletorArquivos.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = seletorArquivos.getSelectedFile();
            System.out.println("CERTO");
        } else {
            System.out.println("File access cancelled by user.");
        }
    }
}
